FROM python:3.11-slim

WORKDIR /app

RUN pip install mlflow scikit-learn --no-cache-dir

COPY mlruns/ /app/mlruns/
COPY mlflow_local.db /app/mlflow_local.db

ENV MLFLOW_TRACKING_URI=sqlite:////app/mlflow_local.db

EXPOSE 8080

CMD ["mlflow", "models", "serve", \
     "--model-uri", "models:/AQI_RandomForest/Production", \
     "--port", "8080", "--host", "0.0.0.0", "--no-conda"]
