FROM python:3.11-slim

WORKDIR /app

RUN pip install mlflow scikit-learn --no-cache-dir

COPY mlruns/ /app/mlruns/
COPY mlflow_local.db /app/mlflow_local.db

ENV MLFLOW_TRACKING_URI=sqlite:////app/mlflow_local.db

EXPOSE 8080

CMD ["mlflow", "models", "serve", "--model-uri", "/app/mlruns/395927815896074895/81f64ce870bc44aaa953efa77c29f565/artifacts/model", "--port", "8080", "--host", "0.0.0.0", "--no-conda"]