name: MLOps Pipeline Automation

on:
  push:
    branches:
      - main
      - feat/mlops-automation

  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Jalankan training model
        run: python src/models/train.py