name: MLOps Pipeline Automation

on:
  push:
    branches:
      - main
      - feat/mlops-automation

  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Jalankan training model
        run: python src/models/train.py